### ISSUE TITLE
[Q] How to print the contents of a Set?

### ISSUE THREAD

**Issue by wsw70** [deckarep/golang-set#110]
I built a Set of `string` and I now would like to print it out

`fmt.Printf("%v", mySet)` outputs `Set{a, b, ...}` but I do not know how to actually get the bare strings inside (to be able, for instance, to `strings.Join()` them)

**Comment by deckarep** [comment]
Hello,

You have a few options: you can either call the ToSlice and convert the set to a slice where you can reference the strings directly.

Or a better way is to just iterate the Set directly using the Each function which takes a callback. This is ideal because you can just leave the set as-is and do updates and then iterate when needed.
