### ISSUE TITLE
[Question] Why isn't `defer` used?

### ISSUE THREAD

**Issue by dharmit** [deckarep/golang-set#125]
Hi, great repo. I'm simply reading through the code for fun. :)

I'm curious to understand why there isn't much use of `defer` to unlock the mutex in `threadsafe.go` because in most of the thread-safe code I've seen, folks prefer using `defer` to not mistakenly forget unlocking stuff.

Is it some kind of design pattern/decision that was consciously made while writing the library?

**Comment by dharmit** [comment]
Ah, I found https://github.com/deckarep/golang-set/pull/14 after opening the issue. I had searched only in the issues, not in PRs. :)

I modified the code to use `defer` everywhere and found that the performance reason still holds true at few places.

**Comment by deckarep** [comment]
Hello,

In general I would say to stick to using `defer` in all typical Go code.
But yes, as you have discovered you can still pay a small performance cost
for it and especially if the code is in a tight loop.

This library could easily be used in a tight loop so it makes sense to try
to make this code as performant as possible (within reason).

Also, since a lot of locking/unlocking is already small in scope (very
small functions) it’s easy to see that `defer` is practically unnecessary
anyway.

I hope that helps!

**Comment by dharmit** [comment]
> Also, since a lot of locking/unlocking is already small in scope (very small functions) it’s easy to see that `defer` is practically unnecessary anyway.

Indeed! And this is something I had in the back of my mind while opening the issue, that it's not a big deal to not have `defer` because of the size of the functions. But I found a few occurrences of `defer` so asked here nonetheless.

But `defer`'s performance penalty was definitely a TIL for me. :)

**Comment by deckarep** [comment]
Well said!

**Comment by Darkheir** [comment]
I think that since [go 1.14](https://go.dev/doc/go1.14#runtime) `defer` doesn't bring any performance penalty:

> This release improves the performance of most uses of defer to incur almost zero overhead compared to calling the deferred function directly. As a result, defer can now be used in performance-critical code without overhead concerns.

Anyway this lib was created long before the 1.14 release :)

**Comment by deckarep** [comment]
I remember this release and the Go team claiming this but later it was actually revealed with more analysis that defer does still have some non-negligible overhead.

At some point I’ll check into this again.
