### ISSUE TITLE
Adding sets with same content to a parent set.

### ISSUE THREAD

**Issue by gsavovski** [deckarep/golang-set#20]
Hello I'm new to Go and your library. 
Consider the following code:

```
package main
import (
    "fmt"
    set "github.com/deckarep/golang-set"
)

func main() {
    s1 := set.NewSet()
    s2 := set.NewSet()
    s1.Add(1)
    s1.Add(2)
    s2.Add(1)
    s2.Add(2)
    parent := set.NewSet()
    parent.Add(s1)
    parent.Add(s2)

    fmt.Println(parent)
}
```

It outputs: 
Set{Set{1, 2}, Set{1, 2}}

Is it possible, for the parent set to recognize that 
s1 and s2 are having the same content and 
add only one? 

Thanks

**Comment by NathanZook** [comment]
This looks to me like a potentially deep conflict.  Go does not like to use containers as keys to maps.
Maps are containers, so if we use a map as a key....
I actually dug into this package to see exactly how this problem is being addressed. :(

It seems to me that the only real option is to use pointers for all structs, maps, arrays, and pointers.  Comparison between these items is then required to be deep.

As for the a & b sets above, the paradox exists only because of appearances.  The set b contains the set a.  The display of a changes because a changes, but b continues to include a.  Note that an additional set c, containing a and 2, is equal to b both before and after a is modified.

**Comment by deckarep** [comment]
This boils down to the fact that keys MUST be comparable types which is limited in Go to simple value types and struct types that don’t contain reference types themselves...ie, they only contain value types or further embed structs which only contain value types.

So the feature request isn’t easily supported in Go given this implementation. I’m going to say this is a fair trade off since the built-in types have the same limitations when it comes to keys and the nature of comparison.
