### ISSUE TITLE
Serialization with gob

### ISSUE THREAD

**Issue by suntong** [deckarep/golang-set#35]
It is possible to make golang-set work with encoding/gob? gob is the good "go to" for serializing things for internal consumption later.

I've prepare a [demo here](https://github.com/suntong/lang/blob/052ca2ae5d6c713c5a7ee75146654dcde3a9e28e/lang/Go/src/ds/Set-Go_Perm.go), currently it is giving out error of:

`SaveState failed:gob: type sync.RWMutex has no exported fields
`

Thanks

**Comment by suntong** [comment]
I took a look, the `sync.RWMutex` is coming from threadsafe.go:

```
type threadSafeSet struct {
	s threadUnsafeSet
	sync.RWMutex
}
```

If, I do mean "if", it is impossible to over come such problem, can we solve this gob saving problem with issue #11 at the same time -- strip out a properly named threadunsafe version, that support gob saving?

**Comment by suntong** [comment]
Well, they all say that closing issues without any explanation is impolite.

**Comment by tiferrei** [comment]
@suntong did you find a solution to this?

**Comment by suntong** [comment]
Why ask me @tiferrei ?!
You should really ask @deckarep what he is thinking!

**Comment by deckarep** [comment]
Hi @tiferrei and @suntong,

I have chosen to close this issue to keep the library fairly straightforward and simple with respect to serving the purpose of a simple set-based datastructure.

Trying to support Gob is outside the concern of this implementation because where do you draw the line with how many serialization/deserialization libs are you going to support?

Furthermore whatever works for Gob might not work with Protobufs (or some other method) and the bottom line is that this largely depends on the types that get added to this datastructure and not really the datastructure itself.

Also Gob is not the defacto serialization method in my opinion.

**Comment by suntong** [comment]
Oh, thanks for the kind explanation. 

Yep, make sense, and I agree with your decision.
