### ISSUE TITLE
Contains function crashed

### ISSUE THREAD

**Issue by rafw** [deckarep/golang-set#44]
type HashSet4String struct {
	set mapset.Set
}

func NewHashSet4String() *HashSet4String {
	var result HashSet4String
	result.set = mapset.NewSet()
	return &result
}

func (s *HashSet4String) Contains(items ...interface{}) bool {
	return s.set.Contains(items)
}

My Contains function will crash, why? Thank you!

**Comment by deckarep** [comment]
Hello @rafw 

The problem is your Contains signature is incorrect:

```go
func (s *HashSet4String) Contains(items ...interface{}) bool {
	return s.set.Contains(items...)
}
```

Notice that the contract requires variadic arguments to the `Contains` function declared in the interface of the internal implementation: https://github.com/deckarep/golang-set/blob/master/set.go#L54

Your signature should match this format to forward the variadic arguments as needed.

Thanks!

**Comment by rafw** [comment]
Thanks a lot!
