### ISSUE TITLE
Extra empty elements in String() and ToSlice() methods

### ISSUE THREAD

**Issue by dgiridharan** [deckarep/golang-set#55]
I think there are extra empty elements in the String() and ToSlice() methods:

```
func (set *threadUnsafeSet) ToSlice() []interface{} {
	keys := make([]interface{}, 0, set.Cardinality())
	for elem := range *set {
		keys = append(keys, elem)
	}

	return keys
}
```

The make call creates an array of the specified size with empty values. For instances if the interface is just an int, it initializes the array with 0s of the specified cardinality. Then the append append() call appends the keys to the end of the array. As a result, all the values get appended.

Would this be better?

```
func (set *threadUnsafeSet) ToSlice() []interface{} {
	var keys []interface{}
	for elem := range *set {
		keys = append(keys, elem)
	}

	return keys
}
```

Or making the slice with the length and then iterating through the slice and assigning to the index value rather than appending to the slice.

**Comment by deckarep** [comment]
Looks like an unintended bug...i'll see if I can get some time to resolve this...

**Comment by deckarep** [comment]
@dgiridharan - can you provide a sample of code that is wrong? This code above is working as intended...

The `keys` slice is created with `make([]interface{}, 0, set.Cardinality())` so if you have a set with a size of 6 then an empty slice is allocated that will have a capacity of 6 by a backing array of a length of 6.  

The slice will be created as empty, and when we append to it it will be of the correct size.

I'm not sure what the issue is?

**Comment by dgiridharan** [comment]
Actually, there's no bug. I'm sorry, looks like it is working fine. This was my mistake.

**Comment by deckarep** [comment]
No problem, thanks for following up.
